version: '3'
services:
  everis-dar-mytasks-ms:
    container_name: MyTasks
    image: "mytasks"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=mytasks
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
    external: true